
version: '3.8'

services:
  agrotech-api:
    build:
      context: .
      dockerfile: ProjectFiles/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=AgroTechDb;Username=postgres;Password=your_password
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: agrotech_postgres
    restart: always
    environment:
      POSTGRES_DB: AgroTechDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
